add scss variables
vartuom/i-am-helping pull request #3
Opened 2023-04-19 11:35 UTC by VadimLitau

- Добавил в зависимости препроцессор SASS
- Немного изменил структуру проекта: 

1. Добавил папку components, в ней создал папку app в которую перенес сгенерированный App.ts. Создал папку example для демонстрации работы SCSS и переменных. Исправил пути для запуска проекта после изменений.
2. Добавил папку constants и в ней создал файл для хранения SCSS переменных. В него же добавил переменные с основными цветами в проекте.

- Проект нормально принимает .scss файлы и работает с ними, генерации лишнего мусора не заметил.

2023-04-19 11:53 UTC, alloya approved these changes

2023-04-19 11:54 UTC, AlexanderSub approved these changes

2023-04-19 14:46 UTC, EremenkoP approved these changes

2023-04-20 05:48 UTC, klmvsn approved these changes

2023-04-20 09:29 UTC, Lakatosska approved these changes

2023-04-20 10:00 UTC, vartuom commented
Обратите внимание, что в реквесте есть конфликты "src/App.tsx". Нужно их порешать или в ветке, или мерджить вручную.

2023-04-20 10:01 UTC, vartuom requested changes
Обратите внимание, что в реквесте есть конфликты "src/App.tsx". Нужно их порешать или в ветке, или мерджить вручную.

2023-04-20 10:17 UTC, vartuom approved these changes

2023-04-20 10:22 UTC, closed without merging