Базовая стилизация чекбокса, без шрифтов
vartuom/i-am-helping pull request #8
Opened 2023-04-21 04:22 UTC by vartuom

2023-04-21 04:43 UTC, klmvsn commented on src/images/check-mark-white.svg
Я бы все-таки попросила, чтобы дизайнер из макета галочку вырезал

2023-04-21 11:23 UTC, AlexanderSub approved these changes

2023-04-21 16:08 UTC, VadimLitau approved these changes

2023-04-22 08:09 UTC, klmvsn approved these changes

2023-04-22 10:20 UTC, msilkov requested changes

2023-04-22 10:20 UTC, msilkov commented on src/components/checkbox/checkbox.module.scss
> +    color: black;
Использовано предопределенное значение цвета. Тк в проекте в основном используются цвета виде hex-значения , предлагаю соблюдать общий стиль кода

2023-04-22 10:20 UTC, msilkov commented on src/components/checkbox/checkbox.module.scss
> +      background: scss-variables.$colorMain url("../../images/check-mark-white.svg") center/contain no-repeat;
для иконок можно создать отдельную папку icons. Пример структуры :
 src/
  images/
    icons/
      icon-1.svg
      icon-2.svg
      ...
    logos/
      logo-1.png
      logo-2.png
      ...
    background/
      bg-1.jpg
      bg-2.jpg
      ...
    ...

2023-04-22 15:10 UTC, merged