fonts + scss variables
vartuom/i-am-helping pull request #9
Opened 2023-04-21 07:49 UTC by VadimLitau

- Добавил в проект файлы со шрифтами.
- Поменял расширения у index.css на index.scss, чтобы можно было пользоваться перуменными.
- Задал по умолчанию для body значения шрифта для декстопной версии

2023-04-22 07:51 UTC, EremenkoP approved these changes

2023-04-22 08:13 UTC, klmvsn approved these changes

2023-04-22 09:41 UTC, msilkov commented on src/fonts/fonts.scss
формат шрифта woff, в пути указан формат ttf

2023-04-22 09:49 UTC, msilkov requested changes

2023-04-22 09:49 UTC, msilkov commented on src/components/app/App.scss
- [ ] значение color. 

- [ ] вынесение цвета в переменную, если цвет используется в нескольких местах в коде, чтобы избежать дублирования кода и легче изменять цвет в будущем.

2023-04-22 09:59 UTC, msilkov requested changes

2023-04-22 09:59 UTC, msilkov commented on src/constants/scss-variables.scss
- [ ] Некоторые цвета, такие как $colorBtnSecond и $colorBtnThird, имеют одинаковые значения. Это может быть опечаткой или ошибкой. Если это необходимо, цвета могут быть переименованы или удалены.

- [ ] Наименование переменных и комменатрии к ним https://nicothin.pro/page/preprocessor-color-functions

2023-04-22 13:03 UTC, VadimLitau commented on src/components/app/App.scss
Это значение было создано CRA, оно используется на странице где идет тестирование компонентов и свойств, в последствии этот компонент будет полностью обновлен

2023-04-22 13:04 UTC, VadimLitau commented on src/constants/scss-variables.scss
Да, действительно, это ошибка

2023-04-22 13:13 UTC, VadimLitau commented
Обновлено

2023-04-23 11:42 UTC, msilkov approved these changes

2023-04-23 11:43 UTC, merged